
  CREATE TABLE "C##PGDITTPS20"."T_BANK" 
   (	"BANKID" NUMBER NOT NULL ENABLE, 
	"BANK" VARCHAR2(20 BYTE), 
	 CONSTRAINT "T_BANK_PK" PRIMARY KEY ("BANKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

======================================================================


  CREATE TABLE "C##PGDITTPS20"."T_DEPARTMENT" 
   (	"DEPARTMENTID" NUMBER NOT NULL ENABLE, 
	"DEPARTMENT" VARCHAR2(20 BYTE), 
	 CONSTRAINT "T_DEPARTMENT_PK" PRIMARY KEY ("DEPARTMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

============================================================================


  CREATE TABLE "C##PGDITTPS20"."T_DOCUMENTTYPE" 
   (	"DOCUMENTTYPEID" NUMBER NOT NULL ENABLE, 
	"DOCUMENT" VARCHAR2(20 BYTE), 
	 CONSTRAINT "T_DOCUMENTTYPE_PK" PRIMARY KEY ("DOCUMENTTYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
===========================================================================

  CREATE TABLE "C##PGDITTPS20"."T_GENDER" 
   (	"GENDERID" NUMBER NOT NULL ENABLE, 
	"GENDER" VARCHAR2(20 BYTE), 
	 CONSTRAINT "T_GENDER_PK" PRIMARY KEY ("GENDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
================================================================================

  CREATE TABLE "C##PGDITTPS20"."T_PROGRAM" 
   (	"PROGRAMID" NUMBER NOT NULL ENABLE, 
	"PROGRAM" VARCHAR2(20 BYTE), 
	"DEPARTMENTID" NUMBER, 
	 CONSTRAINT "T_PROGRAM_PK" PRIMARY KEY ("PROGRAMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "T_PROGRAM_T_DEPARTMENT_FK1" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "C##PGDITTPS20"."T_DEPARTMENT" ("DEPARTMENTID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
================================================================================

  CREATE TABLE "C##PGDITTPS20"."T_PROVIDEDDOCUMENT" 
   (	"PID" NUMBER NOT NULL ENABLE, 
	"ISSUEDATE" DATE, 
	"BANKRECEIPTNO" VARCHAR2(20 BYTE), 
	"DOCUMENTTYPEID" NUMBER, 
	"STUDENTID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "T_PROVIDEDDOCUMENT_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_DOCUMENTTYPEID" FOREIGN KEY ("DOCUMENTTYPEID")
	  REFERENCES "C##PGDITTPS20"."T_DOCUMENTTYPE" ("DOCUMENTTYPEID") ENABLE, 
	 CONSTRAINT "T_PROVIDEDDOCUMENT_T_STUD_FK1" FOREIGN KEY ("STUDENTID")
	  REFERENCES "C##PGDITTPS20"."T_STUDENT" ("STUDENTID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "C##PGDITTPS20"."T_PROVIDEDDOCUMENT" 
   (	"PID" NUMBER NOT NULL ENABLE, 
	"ISSUEDATE" DATE, 
	"BANKRECEIPTNO" VARCHAR2(20 BYTE), 
	"DOCUMENTTYPEID" NUMBER, 
	"STUDENTID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "T_PROVIDEDDOCUMENT_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_DOCUMENTTYPEID" FOREIGN KEY ("DOCUMENTTYPEID")
	  REFERENCES "C##PGDITTPS20"."T_DOCUMENTTYPE" ("DOCUMENTTYPEID") ENABLE, 
	 CONSTRAINT "T_PROVIDEDDOCUMENT_T_STUD_FK1" FOREIGN KEY ("STUDENTID")
	  REFERENCES "C##PGDITTPS20"."T_STUDENT" ("STUDENTID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
=======================================================================

  CREATE TABLE "C##PGDITTPS20"."T_RELIGION" 
   (	"RELIGIONID" NUMBER NOT NULL ENABLE, 
	"RELIGION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "T_RELIGION_PK" PRIMARY KEY ("RELIGIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
===========================================================================

  CREATE TABLE "C##PGDITTPS20"."T_STUDENT" 
   (	"STUDENTID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STUDENTNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"FATHERNAME" VARCHAR2(20 BYTE), 
	"MOTHERNAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"NID" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"CONTACTNO" VARCHAR2(20 BYTE), 
	"DOB" DATE, 
	"IMAGE" BLOB, 
	"ACCOUNTNO" NUMBER, 
	"GENDERID" NUMBER, 
	"RELIGIONID" NUMBER, 
	"BANKID" NUMBER, 
	"BATCHNO" NUMBER, 
	"SESSIONYEAR" VARCHAR2(20 BYTE), 
	"CGPA" NUMBER, 
	"PROGRAMID" NUMBER, 
	 CONSTRAINT "T_STUDENT_PK" PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_GENDERID" FOREIGN KEY ("GENDERID")
	  REFERENCES "C##PGDITTPS20"."T_GENDER" ("GENDERID") ENABLE, 
	 CONSTRAINT "T_STUDENT_T_RELIGION_FK1" FOREIGN KEY ("RELIGIONID")
	  REFERENCES "C##PGDITTPS20"."T_RELIGION" ("RELIGIONID") ENABLE, 
	 CONSTRAINT "T_STUDENT_T_BANK_FK1" FOREIGN KEY ("BANKID")
	  REFERENCES "C##PGDITTPS20"."T_BANK" ("BANKID") ENABLE, 
	 CONSTRAINT "FK_PROGRAMID" FOREIGN KEY ("PROGRAMID")
	  REFERENCES "C##PGDITTPS20"."T_PROGRAM" ("PROGRAMID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

