--------------------------------------------------------
--  File created - Tuesday-December-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_BANK
--------------------------------------------------------

  CREATE TABLE "C##PGDITTPS20"."T_BANK" 
   (	"BANKID" NUMBER, 
	"BANK" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "C##PGDITTPS20"."T_DEPARTMENT" 
   (	"DEPARTMENTID" NUMBER, 
	"DEPARTMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_DOCUMENTTYPE
--------------------------------------------------------

  CREATE TABLE "C##PGDITTPS20"."T_DOCUMENTTYPE" 
   (	"DOCUMENTTYPEID" NUMBER, 
	"DOCUMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GENDER
--------------------------------------------------------

  CREATE TABLE "C##PGDITTPS20"."T_GENDER" 
   (	"GENDERID" NUMBER, 
	"GENDER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PROGRAM
--------------------------------------------------------

  CREATE TABLE "C##PGDITTPS20"."T_PROGRAM" 
   (	"PROGRAMID" NUMBER, 
	"PROGRAM" VARCHAR2(20 BYTE), 
	"DEPARTMENTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PROVIDEDDOCUMENT
--------------------------------------------------------

  CREATE TABLE "C##PGDITTPS20"."T_PROVIDEDDOCUMENT" 
   (	"PID" NUMBER, 
	"ISSUEDATE" DATE, 
	"BANKRECEIPTNO" VARCHAR2(20 BYTE), 
	"DOCUMENTTYPEID" NUMBER, 
	"STUDENTID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_RELIGION
--------------------------------------------------------

  CREATE TABLE "C##PGDITTPS20"."T_RELIGION" 
   (	"RELIGIONID" NUMBER, 
	"RELIGION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_STUDENT
--------------------------------------------------------

  CREATE TABLE "C##PGDITTPS20"."T_STUDENT" 
   (	"STUDENTID" VARCHAR2(20 BYTE), 
	"STUDENTNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"FATHERNAME" VARCHAR2(20 BYTE), 
	"MOTHERNAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"NID" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"CONTACTNO" VARCHAR2(20 BYTE), 
	"DOB" DATE, 
	"IMAGE" BLOB, 
	"ACCOUNTNO" NUMBER, 
	"GENDERID" NUMBER, 
	"RELIGIONID" NUMBER, 
	"BANKID" NUMBER, 
	"BATCHNO" NUMBER, 
	"SESSIONYEAR" VARCHAR2(20 BYTE), 
	"CGPA" NUMBER, 
	"PROGRAMID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into C##PGDITTPS20.T_BANK
SET DEFINE OFF;
REM INSERTING into C##PGDITTPS20.T_DEPARTMENT
SET DEFINE OFF;
Insert into C##PGDITTPS20.T_DEPARTMENT (DEPARTMENTID,DEPARTMENT) values (1,'iit');
Insert into C##PGDITTPS20.T_DEPARTMENT (DEPARTMENTID,DEPARTMENT) values (2,'mathametics');
REM INSERTING into C##PGDITTPS20.T_DOCUMENTTYPE
SET DEFINE OFF;
Insert into C##PGDITTPS20.T_DOCUMENTTYPE (DOCUMENTTYPEID,DOCUMENT) values (1,'testimonial');
REM INSERTING into C##PGDITTPS20.T_GENDER
SET DEFINE OFF;
Insert into C##PGDITTPS20.T_GENDER (GENDERID,GENDER) values (1,'Male');
Insert into C##PGDITTPS20.T_GENDER (GENDERID,GENDER) values (2,'Female');
Insert into C##PGDITTPS20.T_GENDER (GENDERID,GENDER) values (3,'Other');
REM INSERTING into C##PGDITTPS20.T_PROGRAM
SET DEFINE OFF;
Insert into C##PGDITTPS20.T_PROGRAM (PROGRAMID,PROGRAM,DEPARTMENTID) values (2,'CSE',1);
Insert into C##PGDITTPS20.T_PROGRAM (PROGRAMID,PROGRAM,DEPARTMENTID) values (3,'MIT',1);
Insert into C##PGDITTPS20.T_PROGRAM (PROGRAMID,PROGRAM,DEPARTMENTID) values (4,'MSSE',1);
Insert into C##PGDITTPS20.T_PROGRAM (PROGRAMID,PROGRAM,DEPARTMENTID) values (1,'PGDIT',1);
REM INSERTING into C##PGDITTPS20.T_PROVIDEDDOCUMENT
SET DEFINE OFF;
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (17,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (33,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (34,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (38,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (41,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (45,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (50,to_date('07-DEC-20','DD-MON-RR'),'875404',1,'2009');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (55,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (4,to_date('07-DEC-20','DD-MON-RR'),null,1,null);
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (5,to_date('07-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (6,to_date('07-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (7,to_date('07-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (8,to_date('07-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (9,to_date('07-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (10,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (12,to_date('07-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (13,to_date('07-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (18,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (23,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (31,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (36,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (40,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (42,to_date('07-DEC-20','DD-MON-RR'),null,1,'2008');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (43,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (44,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (46,to_date('07-DEC-20','DD-MON-RR'),'875404',1,'2009');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (54,to_date('07-DEC-20','DD-MON-RR'),'875404',1,'2009');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (11,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (15,to_date('07-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (16,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (19,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (20,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (21,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (22,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (24,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (25,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (26,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (27,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (28,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (29,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (30,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (32,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (35,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (37,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (39,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (47,to_date('07-DEC-20','DD-MON-RR'),'4566458579',1,'2008');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (48,to_date('07-DEC-20','DD-MON-RR'),'5768567',1,'2008');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (49,to_date('07-DEC-20','DD-MON-RR'),'875404',1,'2009');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (51,to_date('07-DEC-20','DD-MON-RR'),'5748079',1,'2008');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (52,to_date('07-DEC-20','DD-MON-RR'),'7798',1,'2008');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (53,to_date('07-DEC-20','DD-MON-RR'),'875404',1,'2009');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (57,to_date('07-DEC-20','DD-MON-RR'),'783950355',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (2,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (3,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2007');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (14,to_date('07-DEC-20','DD-MON-RR'),'7568996',1,'2006');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (1,to_date('06-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
Insert into C##PGDITTPS20.T_PROVIDEDDOCUMENT (PID,ISSUEDATE,BANKRECEIPTNO,DOCUMENTTYPEID,STUDENTID) values (56,to_date('07-DEC-20','DD-MON-RR'),'7839503',1,'pgdit2005');
REM INSERTING into C##PGDITTPS20.T_RELIGION
SET DEFINE OFF;
Insert into C##PGDITTPS20.T_RELIGION (RELIGIONID,RELIGION) values (1,'Islam');
Insert into C##PGDITTPS20.T_RELIGION (RELIGIONID,RELIGION) values (2,'Hindu');
Insert into C##PGDITTPS20.T_RELIGION (RELIGIONID,RELIGION) values (3,'Christian');
Insert into C##PGDITTPS20.T_RELIGION (RELIGIONID,RELIGION) values (4,'Buddhism');
REM INSERTING into C##PGDITTPS20.T_STUDENT
SET DEFINE OFF;
Insert into C##PGDITTPS20.T_STUDENT (STUDENTID,STUDENTNAME,PASSWORD,FATHERNAME,MOTHERNAME,ADDRESS,NID,EMAIL,CONTACTNO,DOB,ACCOUNTNO,GENDERID,RELIGIONID,BANKID,BATCHNO,SESSIONYEAR,CGPA,PROGRAMID) values ('2007','mimma aaaa','a','md.awlad hossain','halima begum','mirpur','327690624','mimma.omi@gmail.com','+880164983289',to_date('01-NOV-91','DD-MON-RR'),44657579,2,1,null,220,'2019-2020',3,2);
Insert into C##PGDITTPS20.T_STUDENT (STUDENTID,STUDENTNAME,PASSWORD,FATHERNAME,MOTHERNAME,ADDRESS,NID,EMAIL,CONTACTNO,DOB,ACCOUNTNO,GENDERID,RELIGIONID,BANKID,BATCHNO,SESSIONYEAR,CGPA,PROGRAMID) values ('2008','mimma aaaa','a','md.awlad hossain','halima begum','mirpur','327690624','mimma.omi@gmail.com','+880164983289',to_date('01-NOV-91','DD-MON-RR'),679825779,2,1,null,20,'2019-2020',2.94,1);
Insert into C##PGDITTPS20.T_STUDENT (STUDENTID,STUDENTNAME,PASSWORD,FATHERNAME,MOTHERNAME,ADDRESS,NID,EMAIL,CONTACTNO,DOB,ACCOUNTNO,GENDERID,RELIGIONID,BANKID,BATCHNO,SESSIONYEAR,CGPA,PROGRAMID) values ('2009','mimma akter','a','md.awlad hossain','halima begum','mirpur','327690624','mimma.omi@gmail.com','+880164983289',to_date('01-NOV-91','DD-MON-RR'),57485095,1,1,null,20,'2019-2020',3.35,3);
Insert into C##PGDITTPS20.T_STUDENT (STUDENTID,STUDENTNAME,PASSWORD,FATHERNAME,MOTHERNAME,ADDRESS,NID,EMAIL,CONTACTNO,DOB,ACCOUNTNO,GENDERID,RELIGIONID,BANKID,BATCHNO,SESSIONYEAR,CGPA,PROGRAMID) values ('pgdit2005','mimma akter omi','a','md.awlad hossain','halima begum','mirpur-1,dhaka-1216','327690624','mimma.omi@gmail.com','+880164983289',to_date('01-NOV-91','DD-MON-RR'),57485095,1,1,null,20,'2019-2020',3.35,3);
Insert into C##PGDITTPS20.T_STUDENT (STUDENTID,STUDENTNAME,PASSWORD,FATHERNAME,MOTHERNAME,ADDRESS,NID,EMAIL,CONTACTNO,DOB,ACCOUNTNO,GENDERID,RELIGIONID,BANKID,BATCHNO,SESSIONYEAR,CGPA,PROGRAMID) values ('2006','mimma akter omi','a','md.awlad hossain','halima begum','mirpur-1,dhaka-1216','327690624','mimma.omi@gmail.com','+880164983289',to_date('01-NOV-91','DD-MON-RR'),0,2,1,null,20,'2019-2020',3.87,4);
--------------------------------------------------------
--  DDL for Index T_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PGDITTPS20"."T_STUDENT_PK" ON "C##PGDITTPS20"."T_STUDENT" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PGDITTPS20"."T_DEPARTMENT_PK" ON "C##PGDITTPS20"."T_DEPARTMENT" ("DEPARTMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_PROVIDEDDOCUMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PGDITTPS20"."T_PROVIDEDDOCUMENT_PK" ON "C##PGDITTPS20"."T_PROVIDEDDOCUMENT" ("PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_PROGRAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PGDITTPS20"."T_PROGRAM_PK" ON "C##PGDITTPS20"."T_PROGRAM" ("PROGRAMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_BANK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PGDITTPS20"."T_BANK_PK" ON "C##PGDITTPS20"."T_BANK" ("BANKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_RELIGION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PGDITTPS20"."T_RELIGION_PK" ON "C##PGDITTPS20"."T_RELIGION" ("RELIGIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_DOCUMENTTYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PGDITTPS20"."T_DOCUMENTTYPE_PK" ON "C##PGDITTPS20"."T_DOCUMENTTYPE" ("DOCUMENTTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index T_GENDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PGDITTPS20"."T_GENDER_PK" ON "C##PGDITTPS20"."T_GENDER" ("GENDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_DEPARTMENT" ADD CONSTRAINT "T_DEPARTMENT_PK" PRIMARY KEY ("DEPARTMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_DEPARTMENT" MODIFY ("DEPARTMENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_STUDENT
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_STUDENT" ADD CONSTRAINT "T_STUDENT_PK" PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_STUDENT" MODIFY ("STUDENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_BANK
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_BANK" ADD CONSTRAINT "T_BANK_PK" PRIMARY KEY ("BANKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_BANK" MODIFY ("BANKID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PROGRAM
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_PROGRAM" ADD CONSTRAINT "T_PROGRAM_PK" PRIMARY KEY ("PROGRAMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_PROGRAM" MODIFY ("PROGRAMID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DOCUMENTTYPE
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_DOCUMENTTYPE" ADD CONSTRAINT "T_DOCUMENTTYPE_PK" PRIMARY KEY ("DOCUMENTTYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_DOCUMENTTYPE" MODIFY ("DOCUMENTTYPEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_RELIGION
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_RELIGION" ADD CONSTRAINT "T_RELIGION_PK" PRIMARY KEY ("RELIGIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_RELIGION" MODIFY ("RELIGIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_GENDER
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_GENDER" ADD CONSTRAINT "T_GENDER_PK" PRIMARY KEY ("GENDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_GENDER" MODIFY ("GENDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PROVIDEDDOCUMENT
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_PROVIDEDDOCUMENT" ADD CONSTRAINT "T_PROVIDEDDOCUMENT_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_PROVIDEDDOCUMENT" MODIFY ("PID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_PROGRAM
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_PROGRAM" ADD CONSTRAINT "T_PROGRAM_T_DEPARTMENT_FK1" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "C##PGDITTPS20"."T_DEPARTMENT" ("DEPARTMENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_PROVIDEDDOCUMENT
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_PROVIDEDDOCUMENT" ADD CONSTRAINT "FK_DOCUMENTTYPEID" FOREIGN KEY ("DOCUMENTTYPEID")
	  REFERENCES "C##PGDITTPS20"."T_DOCUMENTTYPE" ("DOCUMENTTYPEID") ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_PROVIDEDDOCUMENT" ADD CONSTRAINT "T_PROVIDEDDOCUMENT_T_STUD_FK1" FOREIGN KEY ("STUDENTID")
	  REFERENCES "C##PGDITTPS20"."T_STUDENT" ("STUDENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_STUDENT
--------------------------------------------------------

  ALTER TABLE "C##PGDITTPS20"."T_STUDENT" ADD CONSTRAINT "FK_GENDERID" FOREIGN KEY ("GENDERID")
	  REFERENCES "C##PGDITTPS20"."T_GENDER" ("GENDERID") ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_STUDENT" ADD CONSTRAINT "FK_PROGRAMID" FOREIGN KEY ("PROGRAMID")
	  REFERENCES "C##PGDITTPS20"."T_PROGRAM" ("PROGRAMID") ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_STUDENT" ADD CONSTRAINT "T_STUDENT_T_BANK_FK1" FOREIGN KEY ("BANKID")
	  REFERENCES "C##PGDITTPS20"."T_BANK" ("BANKID") ENABLE;
  ALTER TABLE "C##PGDITTPS20"."T_STUDENT" ADD CONSTRAINT "T_STUDENT_T_RELIGION_FK1" FOREIGN KEY ("RELIGIONID")
	  REFERENCES "C##PGDITTPS20"."T_RELIGION" ("RELIGIONID") ENABLE;
--------------------------------------------------------
--  DDL for Procedure GETGENDERLOOKUP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PGDITTPS20"."GETGENDERLOOKUP" 
(
data_cursor in out pReturnData.c_records,
pstudentid in varchar2
)
as
begin
open data_cursor for
SELECT b.genderid,b.gender
FROM t_student a,t_gender b
where a.genderid=b.genderid
and a.studentid=pstudentid
order by b.gender
;
end Getgenderlookup;

/
--------------------------------------------------------
--  DDL for Procedure GETSTUDENTINFO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PGDITTPS20"."GETSTUDENTINFO" 
(
pstudentid in varchar2
)
as
begin
SELECT * 
FROM t_student a,t_gender b
where a.genderid=b.genderid
and a.studentid=pstudentid
;
end GetStudentInfo;

/
--------------------------------------------------------
--  DDL for Procedure INSERTPROVIDEDDOCRECORD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PGDITTPS20"."INSERTPROVIDEDDOCRECORD" 
(
pbankrecno in number,
pStdid in varchar2
)
as
begin
INSERT INTO T_PROVIDEDDOCUMENT (PID, ISSUEDATE, BANKRECEIPTNO, DOCUMENTTYPEID, STUDENTID)
VALUES ((select max(pid)+1 from t_provideddocument), TO_DATE(sysdate, 'DD-MON-RR'), pbankrecno, '1', pStdid);
end InsertProvideddocRecord;

/
--------------------------------------------------------
--  DDL for Procedure UPDATESTUDENTDETAILS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##PGDITTPS20"."UPDATESTUDENTDETAILS" 
(
pstdname in varchar2,
pStdid in varchar2,
pContactno in varchar2,
pAddress in varchar2,
pEmail in varchar2,
pAccno in number,
pFathername in varchar2,
pMothername in varchar2,
pNid in varchar2

)
as
begin
update t_student set studentname=pstdname,accountno=paccno
,address=paddress,fathername=pfathername
,email=pemail,mothername=pmothername 
,contactno=pcontactno,nid=pnid
where studentid=pStdid;
end UpdateStudentDetails;

/
